# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stars}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zach Holman"]
  s.date = %q{2010-03-25}
  s.default_executable = %q{stars}
  s.description = %q{Recent favstar faves on your command line.}
  s.email = %q{github.com@zachholman.com}
  s.executables = ["stars"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/stars",
     "lib/stars.rb",
     "lib/stars/client.rb",
     "lib/stars/favstar.rb",
     "lib/stars/formatter.rb",
     "stars.gemspec",
     "test/helper.rb",
     "test/test_client.rb",
     "test/test_favstar.rb",
     "test/test_formatter.rb",
     "test/test_stars.rb"
  ]
  s.homepage = %q{http://github.com/holman/stars}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Recent favstar faves on your command line}
  s.test_files = [
    "test/helper.rb",
     "test/test_client.rb",
     "test/test_favstar.rb",
     "test/test_formatter.rb",
     "test/test_stars.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<terminal-table>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<terminal-table>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<terminal-table>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

